services:
  api01: &api
    entrypoint:
    - sleep
    - infinity
    image: thiper01/api-djanguitos-rinha2024-q1
    hostname: api01
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    environment:
      - DB_HOSTNAME=db
      - PORT=3000
    ports:
      - "3001:3000"
    depends_on:
      - db

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1